6.7. Приёмочное тестирование
htmlacademy-php3/2069609-what-to-watch-2 pull request #10
Opened 2023-04-12 12:23 UTC by delannushka

2023-04-18 06:11 UTC, selyatin83 requested changes

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/AddFilmFromRepository.php
> +        $movieRepository = new OmdbRepository($client);
Необходимо испольовать внедрение зависимостей, и в лучше случае избавлять от прямого создания через new

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/AddFilmFromRepository.php
> +    public static function getFilmInfo($imdbId): array
Почему метод решила сделать статичный?

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/GetFilmInfo.php
> +    public static function getInfo($id) {
Нужна типизация для входных аргументов метода

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/GetFilmInfo.php
> +    public static function getInfo($id) {
Нужен PHPDoc для написанных тобою методов

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/GetFilmInfo.php
> +        $film = Film::find($id);
Нужна проверка на существовании фильма, если он отсутствует то код с 13й строки упадет

2023-04-18 06:11 UTC, selyatin83 commented on app/Handler/GetFilmInfo.php
> +        return [
Для подобных ситуаций, лучше использовать DTO

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +        $comments = DB::table('users')
бизнес логика в контроллерах по техническим требованиям проекта запрещена, это нужно вынести в сервис или репозиторий комментариев

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +            }
Ты думаешь такой кейс возможен? Проверяла? 
Мне кажется роутинг Laravel не даст такой кейс воспроизвести, и просто кинет 404 ошибку

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +        $comments = DB::table('users')
Почему решила использовать запрос через DB, а не через модель orm?

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +    public function destroy($commentId): BaseResponse
Лучше указывать тип входного аргумента, laravel преобразует его сразу перед отдачей в метод контроллера
int $commentId

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +            }
В контроллере не должно быть бизнес-логике, можно, к примеру, вынести в сервис комментариев и назвать метод по его функционалу

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            $film = AddFilmFromRepository::getFilmInfo($imdbId);
Статические методы не всегда есть хорошо, расскажи, почему ты их так частно используешь?
Какие ты в этом видишь плюсы/минусы ?

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            $addFilm = Film::find($addFilmId);
Film::create вернет сохраненную модель фильма, этот код излишен

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +                DB::delete('delete from film_genre where film_id = ?', [$filmId]);
Почему используешь DB? Почему не через ORM?

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +    public function update(FilmUpdateRequest $request, $filmId): BaseResponse
В этом методе нужно соблюсти гарантии, что все данные успешно будут согласованы. 
Сейчас этой гарантии нет, чтобы она была здесь нужно использовать транзакцию

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            }
Запросы в цикле использовать не рекомендуется, попробуй это объединить в один запрос.
Почему не рекомендуется - неизвестно кол-во итераций,  каждая итерация - запрос в бд, что создает неожидаемую нагрузку в N запросов.

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            }
Здесь речь только пока что про выборку в цикле, про изменение, можно, но под транзакцией

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            }
Выборка в цикле, нужно подумать над тем, как это можно поменять

2023-04-18 06:11 UTC, selyatin83 commented on app/Http/Controllers/FilmController.php
> +            $filmIdsForShow = array_slice($uniqueSimilarFilmsIds, 0, 4);
Бизнес логика в контроллере - запрещено

2023-04-19 15:57 UTC, delannushka commented on app/Handler/GetFilmInfo.php
> +        $film = Film::find($id);
У меня проверка этого есть в самом контроллере, сюда заведомо попадает существующий id, все равно проверка нужна?

2023-04-20 11:19 UTC, delannushka commented on app/Http/Controllers/CommentController.php
> +            }
Проверила! И конечно же ты прав=)

2023-04-25 07:19 UTC, selyatin83 commented on app/Handlers/Permission.php
> +        if ($user->id === $comment->user_id){
`return $user->id === $commect->user_id;`

2023-04-25 07:20 UTC, selyatin83 commented on app/Http/Controllers/AuthController.php
> +     * Доступно залогиненным пользователям
Такие комментарии излишне, по коду и структуре роутов можно понять доступ к методу

2023-04-25 07:58 UTC, selyatin83 requested changes

2023-04-25 07:58 UTC, selyatin83 commented on app/Http/Controllers/CommentController.php
> +            }
Нарушен PSR, открывающая фигурная скобка должна быть на строчке с if

2023-04-25 07:58 UTC, selyatin83 commented on app/Http/Repositories/AddFilmFromRepository.php
> +     */
Комментарий к чему относится? 
К конструктору? 

Нужно правильно его расположить

2023-04-25 07:58 UTC, selyatin83 commented on app/Http/Repositories/AddFilmFromRepository.php
> +class AddFilmFromRepository
А почему нельзя сразу вызывать Репозиторий omdb? Зачем лишная обертка?

2023-04-25 07:58 UTC, selyatin83 commented on app/Http/Requests/BaseRequestApi.php
> +            //ошибка 422
Такие комментарии излишне,  недоносят информации, только заполняют место
Комментарии нужны только там где сложная логика или сложно догодаться что происходит

В таких местах можно понять по коду, что это за ошибка

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +        $omdbRepository = new OmdbRepository($client);
Давай лучше это перенесем в контейнер-зависимостей и будем получать репозиторий из аргументов метода

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +        $omdbRepository = new OmdbRepository($client);
Если нужна консультация, давай запланируем созвон

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +        $omdbFilm = new AddFilmFromRepository($omdbRepository, $imdbId);
И это тоже

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +        $omdbFilm = new AddFilmFromRepository($omdbRepository, $imdbId);
Предлагаю созвониться сразу и разберем этот кейс и я покажу как это работает и зачем нужно

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +        }
Зачем здесь транзакция? В БД не вносятся изменения

2023-04-25 07:58 UTC, selyatin83 commented on app/Services/FilmService.php
> +                $films[] = $this->showInfoAboutFilm(idFilm: $filmIdForShow);
Запросы (select) в цикле не рекомендуется использовать, особенно на такие большие данные
Давай попробуем найти другое решение

2023-04-30 14:56 UTC, merged